### ISSUE TITLE
get_free_gpu_ids() with default arguments never returns a GPU

### ISSUE THREAD

**Issue by EaiPool** [lorenz-h/nvsmpy_V1#3]
When I do a query for utilization.gpu or utilization.memory, the returned value is a percentage (i.e. a number between 0 and 100). 
The default filters values in get_free_gpu_ids() are 0.1 and 0.5, respectively, resulting in filtering out almost every gpu, every single time.
I noticed you tested this for nvidia-smi versions higher than mine (410.79), so it could be that the output changed since then. 
If that is the case, I can make a pull-request to fix this for my version of nvidia-smi, making it more backwards compatible.

**Comment by EaiPool** [comment]
Either way, perhaps it makes more sense to use "memory.free" instead of "utilization.memory" by default?

**Comment by lorenz-h** [comment]
New versions also return an integer in range(0,100) (my bad). I fixed the default values in Commit bd7421e1ce4c42dd12b5fc07c9b15d78c529736e
